const concerts = [
  {
    id: 1,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Bijan-Mortazavi-1024x683.webp",
    artist: "Bijan Mortazavi Violin Grand Master Senfoni Orkestrası",
    city: "istanbul",
    location: "istanbul Kongre Merkezi Harbiye Oditoryumu",
    date: "07/09/2023",
    time: "20:30",
    ticket: "Biletix",
    description:
      "Bijan Mortazavi, unutulmaz performansları ve büyüleyici müziğiyle dünya çapında ün kazanmış bir virtüöz olarak, senfoni orkestrasıyla birlikte sahneye çıkacak. Bu benzersiz etkinlikte, Bijan Mortazavi’nin hayranları, klasik müziğin gücünü ve duygusal derinliğini deneyimleyecekler. Violinin büyülü notaları, Senfoni Orkestrası’nın zengin ve etkileyici sesleriyle buluşarak dinleyicilere unutulmaz bir performans sunacak. Unutulmaz bir geceye tanıklık etmek, müziğin büyüsüyle kendinizi kaybetmek ve Bijan Mortazavi’nin çığır açan performansını deneyimlemek için bu eşsiz etkinliği kaçırmayın!",
  },
  {
    id: 2,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Combolatino-1024x538.webp",
    artist: "Combolatino",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "09/09/2023",
    time: "20:30",
    ticket: "Passo",
    description:
      "Combolatino, yüksek enerjili canlı müziği ile eğlenmek isteyen herkesi 9 Eylül Cumartesi akşamı Zorlu PSM Sky Lounge’a bekliyor.",
  },
  {
    id: 3,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/cem-adrian.webp",
    artist: "Cem Adrian",
    city: "istanbul",
    location: "Hayal Kahvesi Aqua Florya",
    date: "09/09/2023",
    time: "22:00",
    ticket: "Biletix",
    description:
      "Müzikte sınırları, tarzları, kuralları dışlayan, kendini sadece “özgür bir müzisyen” olarak tanımlayan Cem Adrian, sevenleriyle buluşmaya devam ediyor.",
  },
  {
    id: 4,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/kenan-dogulu.webp",
    artist: "Kenan Doğulu",
    city: "istanbul",
    location: "Turkcell Vadi",
    date: "10/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description:
      "Pop müziğin sevilen ismi Kenan Doğulu, sevilen şarkılarıyla Turkcell Vadi Sahnesi’nde!",
  },
  {
    id: 5,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/ayda-sozeri.webp",
    artist: "Ayta Sözeri",
    city: "istanbul",
    location: "Dada Salon Kabarett",
    date: "13/09/2023",
    time: "22:00",
    ticket: "Passo",
    description:
      "Okan Bayülgen’in istanbul’a kazandırdığı sıra dışı gösteri mekanı Dada Salon Kabarett Ayta Sözeri’yi ağırlıyor!",
  },
  {
    id: 6,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/feridun-duzagac-1-1024x576.webp",
    artist: "Feridun Düzağaç",
    city: "istanbul",
    location: "IF Performans Hall Beşiktaş",
    date: "15/09/2023",
    time: "21:30",
    ticket: "Passo",
    description:
      "Rock müziğin sevilen ismi Feridun Düzağaç, istanbullu müzikseverlerle buluşuyor.",
  },
  {
    id: 7,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/ceylan-ertem.webp",
    artist: "Ceylan Ertem",
    city: "istanbul",
    location: "Jolly Joker Kıyı istanbul",
    date: "15/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description: "Ceylan Ertem, 15 Eylül’de Jolly Joker Kıyı istanbul’da.",
  },
  {
    id: 8,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/emre-aydin-1.webp",
    artist: "Emre Aydın",
    city: "istanbul",
    location: "Mask Beach",
    date: "15/09/2023",
    time: "22:00",
    ticket: "Biletix",
    description:
      "Rock müziğin sevilen ismi Emre Aydın, 15 Eylül akşamı Mask Beach Beylikdüzü Sahnesi’nde.",
  },
  {
    id: 9,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Eli-Fur-1024x683.webp",
    artist: "Beatgate Presents: Eli & Fur",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "16/09/2023",
    time: "20:00",
    ticket: "Passo",
    description:
      "Coachella, Tomorrowland ve Ultra Music Festival’lerindeki sahneleriyle göz dolduran Eli & Fur, benzersiz müzikal etkileşimleri ve Beatgate’in 17 yıllık mirasıyla, sıradan etkinliklerin ötesinde bir deneyim sunmayı vadeden özel bir performansla sahne almaya hazırlanıyor.",
  },
  {
    id: 10,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/tamino-1024x576.webp",
    artist: "Tamino",
    city: "istanbul",
    location: "Parkorman",
    date: "17/09/2023",
    time: "18:00",
    ticket: "Passo",
    description:
      "Daha önce Parkorman ve Volkswagen Arena’daki performanslarıyla öte dünyalara adeta bir portal açılmasına sebep olan; sahnedeki dev varlığıyla seyircileri serseme çeviren Tamino, Türkiye turnesinin kapanışını yapmak için istanbul’da.",
  },
  {
    id: 11,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/gipsy-kings.webp",
    artist: "Gipsy Kings",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "19/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Albümleri 60 milyon satan, sahnede 30 yıllık başarılarla dolu bir müzik kariyerini geride bırakan Latin müziğinin en çok sevilen grubu, Grammy Ödüllü Gipsy Kings, Andre Reyes öncülüğünde 19 Eylül akşamı Zorlu PSM Turkcell Sahnesi’nde!",
  },
  {
    id: 12,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/zuhal-olcay.webp",
    artist: "Zuhal Olcay ile Ormanda Jazz",
    city: "istanbul",
    location: "YBY Woods Yaşam ve Etkinlik Alanı",
    date: "20/09/2023",
    time: "21:00",
    ticket: "biletinial",
    description:
      "Duru sesi ve dinamizmi ile büyük beğeni toplayan Zuhal Olcay, YBY Woods/Kemerburgaz Kent Ormanı’nda en sevilen şarkılarını seslendirmeye hazırlanıyor.",
  },
  {
    id: 13,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/sertab_erener-1.webp",
    artist: "Sertab Erener",
    city: "istanbul",
    location: "Maximum UNIQ Açıkhava",
    date: "20/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Türk müziğinin yıldız sanatçısı Sertab Erener, Bkm Yaz Etkinlikleri kapsamında, son albümü ‘Ben Yaşarım’ ve geçmişten günümüze gelen sevilen şarkılarını Bkm organizasyonu ile 20 Eylül’de Maximum Uniq Açıkhava’da söyleyecek.",
  },
  {
    id: 14,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Armin-Van-Buuren.webp",
    artist: "Armin Van Buuren",
    city: "istanbul",
    location: "Life Park",
    date: "22/09/2023",
    time: "16:00",
    ticket: "Passo",
    description:
      "DJ MAG’de 5 kez dünyanın en iyi Dj’i seçilen ve 20 yıldan uzun süren müzik kariyerinde sürekli zirvede yer alan Grammy ödüllü, Trance müziğin dünyadaki neferi ve EDM’in dünyadaki en etkili figürü, Ultra Music, Tomorrowland, Untold gibi dünyanın en büyük festivallerinin yıllardır değişmeyen headliner’i Armin Van Buuren, 22 Eylül cuma gecesi Lifepark Sahnesi’nde!",
  },
  {
    id: 15,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/teoman-1-1024x640.webp",
    artist: "Teoman",
    city: "istanbul",
    location: "Harbiye Cemil Topuzlu Açıkhava Tiyatrosu",
    date: "22/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Teoman’ın kariyerinde biriktirdiği çok özel hikâyelere ortak olmak ve en koyu şarkılarının en koyu versiyonlarını dinlemek için bu müzik dolu geceye davetlisiniz.",
  },
  {
    id: 16,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Kerem-Gorsev-Trio-1024x683.webp",
    artist: "Single Circle presents: Kerem Görsev Trio",
    city: "istanbul",
    location: "Zorlu PSM – Touche",
    date: "22/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "﻿Caz dünyasının önde gelen isimlerinden Kerem Görsev, kontrbasta Volkan Hürsever, davulda Ferit Odman’dan oluşan trio ekibiyle 22 Eylül’de Touché’de!",
  },
  {
    id: 17,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Oscar-And-The-Wolf-1-1024x677.webp",
    artist: "Oscar And The Wolf",
    city: "istanbul",
    location: "KüçükÇiftlik Park",
    date: "23/09/2023",
    time: "18:00",
    ticket: "biletinial",
    description:
      "Indie pop’un fenomen gruplarından Oscar and the Wolf, yeniden istanbul’da.",
  },
  {
    id: 18,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/Asaf-Avidan.webp",
    artist: "Asaf Avidan",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "23/09/2023",
    time: "21:30",
    ticket: "Passo",
    description:
      "Kendine has şarkıları, şarmant hikayeleri ve enerjik çoklu enstrümantal becerileri arasında mükemmel bir şekilde gezinen Avidan, “ICHONOLOGY Solo Tour 2023” kapsamında istanbul’a geliyor!",
  },
  {
    id: 19,
    artist: "Can Bonomo",
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/can-bonomo-1024x576.webp",
    city: "istanbul",
    location: "YBY Woods Yaşam ve Etkinlik Alanı",
    date: "23/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Can Bonomo, sevilen şarkılarını seslendirmek için YBY Woods Yaşam ve Etkinlik Alanı’nda sevenleriyle buluşuyor.",
  },
  {
    id: 20,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/fikri-karayel-1024x683.webp",
    artist: "Fikri Karayel Jazz Ensemble",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "23/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Müzik kariyerinin başından beri caz soundlarını her daim cebinde taşıyan sanatçı, caz sahnesinin değerli müzisyenlerinden oluşan ekibiyle 23 Eylül akşamı Touché’de.",
  },
  {
    id: 21,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/buika.webp",
    artist: "Buika",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "26/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Gelmiş geçmiş en iyi vokaller arasında gösterilen Grammy Ödüllü Buika, flamenko, soul ve cazı harmanladığı görkemli müziği ile müzikseverlere muhteşem bir müzik şöleni yaşatmak için istanbul’da.",
  },
  {
    id: 22,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/sila.webp",
    artist: "Sıla",
    city: "istanbul",
    location: "Harbiye Cemil Topuzlu Açıkhava Tiyatrosu",
    date: "28/09/2023",
    time: "21:15",
    ticket: "Passo",
    description:
      "Sıla, sevilen şarkılarını dinleyicisiyle buluşturmaya hazırlanıyor.",
  },
  {
    id: 23,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/pinhani.webp",
    artist: "Pinhani",
    city: "istanbul",
    location: "KüçükÇiftlik Park",
    date: "29/09/2023",
    time: "19:30",
    ticket: "Biletix",
    description:
      "Melodileri içimizi ısıtan, sözleri umut veren, sadeliği yüreklerimize iyi gelen şarkılarıyla Pinhâni, artık bir gelenek halini alan eylül konseri için yeniden KüçükÇiftlik Park’ta!",
  },
  {
    id: 24,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Riverside-1024x683.webp",
    artist: "Riverside",
    city: "istanbul",
    location: "IF Performance Hall Beşiktaş",
    date: "29/09/2023",
    time: "21:30",
    ticket: "Passo",
    description:
      "Polonya’nın karizmatik progresif rock/metal grubu Riverside, ID.Entity Avrupa Turnesi kapsamında IF Beşiktaş’a geliyor!",
  },
  {
    id: 25,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/2PO25-1024x564.webp",
    artist: "SM Loves2Dance: Kollektiv Turmstrasse & Gerd Janson",
    city: "istanbul",
    location: "Zorlu PSM",
    date: "29/09/2023",
    time: "20:00",
    ticket: "Passo",
    description:
      "Elektronik müziğin önde gelen ikililerinden Kollektiv Turmstrasse, Gerd Janson ve Marc Gonen ile PSM Loves2Dance kapsamında 29 Eylül’de Zorlu PSM Turkcell Sahnesi’ni dans pistine çevirmeye geliyor.",
  },
  {
    id: 26,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/kalben-1024x576.webp",
    artist: "Kalben",
    city: "istanbul",
    location: "Dorock XL Kadıköy",
    date: "29/09/2023",
    time: "21:30",
    ticket: "Biletix",
    description: "Kalben , 29 Eylül tarihinde Dorock XL Kadıköy sahnesinde.",
  },
  {
    id: 27,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/la-femme.webp",
    artist: "La Femme",
    city: "istanbul",
    location: "Salon İKSV",
    date: "29/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "L’impératrice’den sonra Fransız saykedelyasına açlığınızın arttığını duyar gibiyiz. Fatale’i isminde gizli La Femme ile Salon’un 2023 sonbahar sezonunu açmaya hazır mısınız?",
  },

  {
    id: 28,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/levent-yuksel-1024x576.webp",
    artist: "Levent Yüksel",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "12/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 29,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/tamino-1024x576-1.webp",
    artist: "Tamino",
    city: "izmir",
    location: "İzmir Arena",
    date: "14/09/2023",
    time: "19:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 30,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/yalin.webp",
    artist: "Yalın",
    city: "izmir",
    location: "Efes Antik Tiyatro",
    date: "15/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 31,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/livaneli-sarkilari.webp",
    artist:
      "Livaneli Şarkıları – Nükhet Duru – Mehmet Erdem – Ferhat Livaneli Orkestrası",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "15/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 32,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/asya-kursat-basar-zafer-cebi.webp",
    artist: "Asya – Kürşat Başar ve Zafer Çebi Orkestrası",
    city: "izmir",
    location: "Bostanlı Suat Taşer Tiyatrosu",
    date: "15/09/2023",
    time: "20:00",
    ticket: "Biletix",
    description: "",
  },
  {
    id: 33,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Dolu-Kadehi-Ters-Tut-1.webp",
    artist: "Dolu Kadehi Ters Tut",
    city: "izmir",
    location: "Efes Antik Tiyatro",
    date: "16/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 34,
    image: "https://wp.oggusto.com/wp-content/uploads/2023/08/hadise-2.webp",
    artist: "Hadise",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "17/09/2023",
    time: "21:30",
    ticket: "Biletix",
    description: "",
  },
  {
    id: 35,
    image:
      "https://wp.oggusto.com/wp-content/uploads/2023/08/Oscar-And-The-Wolf-1-1024x677-1.webp",
    artist: "Oscar And The Wolf",
    city: "izmir",
    location: "İzmir Arena",
    date: "21/09/2023",
    time: "18:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 36,
    artist: "Gülşen",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "22/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description: "",
  },
  {
    id: 37,
    artist: "Teoman’ın Koyu Antoloji’si",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "23/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 38,
    artist: "Ajda Pekkan",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "26/09/2023",
    time: "21:15",
    ticket: "Passo",
    description: "",
  },
  {
    id: 39,
    artist: "Evgeny Grinko",
    city: "izmir",
    location: "İzmir Kültürpark Açıkhava Tiyatrosu",
    date: "29/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "",
  },
  {
    id: 40,
    artist: "Nuri Harun Ateş | Baroque Cabaret",
    city: "izmir",
    location: "Hikmet Şimşek Sanat Merkezi",
    date: "30/09/2023",
    time: "20:30",
    ticket: "Passo",
    description: "",
  },
  {
    id: 41,
    artist: "Kenan Doğulu",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "01/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Pop müziğin efsanevi ismi Kenan Doğulu, Ankaralı hayranlarıyla buluşuyor.",
  },
  {
    id: 42,
    artist: "Seksendört",
    city: "Ankara",
    location: "ODTÜ Mezunlar Derneği Vişnelik Tesisi",
    date: "01/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description:
      "Seksendört, ODTÜ Açıkhava Sahnesi’nde sevenleriyle buluşuyor.",
  },
  {
    id: 43,
    artist: "Su Sonia",
    city: "Ankara",
    location: "IF Performance Hall",
    date: "01/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description:
      "Su Sonia’nın konseri, AGA B ve DJ SUPPA’nın da konuk sanatçı olarak yer alacağı Ankara IF Performance Sahnesi’nde.",
  },
  {
    id: 44,
    artist: "An Epic Symphony & Hayko Cepkin",
    city: "Ankara",
    location: "CerModern Açık Hava",
    date: "02/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Events Across Turkey’in uluslararası ödüllü projesi An Epic Symphony, rock müziğin sevilen ismi Hayko Cepkin’i Night Flight Symphony Orchestra & Choir eşliğinde ağırlıyor.",
  },
  {
    id: 45,
    artist: "Athena",
    city: "Ankara",
    location: "Armada AVM Açıkhava",
    date: "03/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Türkiye’nin en çok sevilen rock gruplarından Athena, sevilen şarkılarını seslendirmek için Ankara’da.",
  },
  {
    id: 46,
    artist: "Müzede Müzik İtalyan Ezgileri – Euridice Pezzotta",
    city: "Ankara",
    location: "Erimtan Arkeoloji ve Sanat Müzesi",
    date: "05/09/2023",
    time: "20:00",
    ticket: "Biletix",
    description:
      "İtalya Büyükelçiliği ve İtalyan Kültür Merkezi işbirliğinde, Erimtan Arkeoloji ve Sanat Müzesi ev sahipliğinde gerçekleşecek olan konser serisi klasik müzikseverleri İtalyan ezgileriyle buluşturuyor.",
  },
  {
    id: 47,
    artist: "Bülent Ortaçgil & Zuhal Olcay",
    city: "Ankara",
    location: "ODTÜ Mezunlar Derneği Vişnelik Tesisi",
    date: "09/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Türk müziğinin önemli iki ismi Bülent Ortaçgil ve Zuhal Olcay Odtü Vişnelik Çim Amfi’de sevenleriyle buluşacak.",
  },
  {
    id: 48,
    artist: "Ayta Sözeri",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "10/09/2023",
    time: "21:15",
    ticket: "Passo",
    description:
      "Ayta Sözeri, KerkiSolfej organizasyonu ile sevilen şarkılarını sizlerle buluşturmaya hazırlanıyor.",
  },
  {
    id: 49,
    artist: "Tamino",
    city: "Ankara",
    location: "ODTÜ Mezunlar Derneği Vişnelik Tesisi",
    date: "13/09/2023",
    time: "19:00",
    ticket: "Passo",
    description:
      "Daha önce Parkorman ve Volkswagen Arena’daki performanslarıyla öte dünyalara adeta bir portal açılmasına sebep olan; sahnedeki dev varlığıyla seyircileri serseme çeviren Tamino, Türkiye’de.",
  },
  {
    id: 50,
    artist: "Buray",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "13/09/2023",
    time: "21:15",
    ticket: "Passo",
    description:
      "Buray, sevilen şarkılarını Ankaralı hayranlarıyla seslendirmek için hazırlanıyor.",
  },
  {
    id: 51,
    artist: "Can Koç",
    city: "Ankara",
    location: "6:45 KK Ankara",
    date: "14/09/2023",
    time: "22:00",
    ticket: "Biletix",
    description: "Can Koç, 6:45 KK Ankara sahnesinde.",
  },
  {
    id: 52,
    artist: "Ajda Pekkan",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "15/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "Pop müziğin süperstarı Ajda Pekkan, Ankara’da.",
  },
  {
    id: 53,
    artist: "Gülşen",
    city: "Ankara",
    location: "ODTÜ Mezunlar Derneği Vişnelik Çim Amfi",
    date: "15/09/2023",
    time: "21:30",
    ticket: "Biletix",
    description:
      "Türk popunun en sevilen isimlerinden Gülşen, ODTÜ MD Vişnelik Çim Amfi sahnesinde.",
  },
  {
    id: 54,
    artist: "Sıla",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "16/09/2023",
    time: "21:00",
    ticket: "Passo",
    description: "Sıla, sevilen şarkılarını Ankara’da seslendirecek.",
  },
  {
    id: 55,
    artist: "Cem Adrian",
    city: "Ankara",
    location: "MEB Şura Salonu",
    date: "17/09/2023",
    time: "20:00",
    ticket: "Biletix",
    description:
      "Müzikte sınırları, tarzları, kuralları dışlayan, kendini sadece “özgür bir müzisyen” olarak tanımlayan Cem Adrian, sevenleriyle buluşmaya devam ediyor.",
  },
  {
    id: 56,
    artist: "Berkay",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "22/09/2023",
    time: "21:15",
    ticket: "Passo",
    description:
      "Berkay, sevilen şarkılarını seslendirmek için Amfi Tiyatrosu sahnesinde.",
  },
  {
    id: 57,
    artist: "Oscar And The Wolf",
    city: "Ankara",
    location: "ODTÜ Mezunlar Derneği Vişnelik Tesisi",
    date: "22/09/2023",
    time: "18:00",
    ticket: "Passo",
    description:
      "Indie pop’un fenomen gruplarından Oscar and the Wolf, Türkiye’de!",
  },
  {
    id: 58,
    artist: "Kalben",
    city: "Ankara",
    location: "Jolly Joker Ankara",
    date: "22/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description: "Kalben, Jolly Joker Ankara sahnesinde.",
  },
  {
    id: 59,
    artist: "Mabel Matiz",
    city: "Ankara",
    location: "CerModern Açık Hava",
    date: "29/09/2023",
    time: "21:00",
    ticket: "Passo",
    description:
      "Mabel Matiz, Atlantis Yapım ve IF ortaklığı ile Ankaralı sevenleriyle buluşuyor!",
  },
  {
    id: 60,
    artist: "Sena Şener",
    city: "Ankara",
    location: "Milyon Performance Hall Ankara",
    date: "29/09/2023",
    time: "21:30",
    ticket: "Biletix",
    description:
      "Büyüleyici sesiyle rock müziğin yükselen isimlerinden Sena Şener, Milyon Performance Hall Sahnesi’nde dinleyicileri ile buluşuyor.",
  },
  {
    id: 61,
    artist: "Sertab Erener",
    city: "Ankara",
    location: "Atılım Üniversitesi Amfi Tiyatro",
    date: "30/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description:
      "Sertab Erener KerkiSolfej organizasyonu ile Ankara’ya geliyor.",
  },
  {
    id: 62,
    artist: "Emre Aydın",
    city: "Ankara",
    location: "Milyon Performance Hall Ankara",
    date: "30/09/2023",
    time: "21:30",
    ticket: "Biletix",
    description: "Emre Aydın, Milyon Performance Hall Ankara Sahnesi’nde.",
  },
  {
    id: 63,
    artist: "Emir Can İğrek",
    city: "Ankara",
    location: "Armada AVM Açıkhava",
    date: "30/09/2023",
    time: "21:00",
    ticket: "Biletix",
    description:
      "Emir Can İğrek, Ankara Armada AVM Açıkhava’da sevenleri ile buluşuyor.",
  },
];

export default concerts;
